const base_url = "/images/sinhnhat11nam/img_main/manh-ghep-min/";

export const list_back = [
  {id: 1, name: 'manh', image: base_url+'A1.png'},
  {id: 2, name: 'manh', image: base_url+'A2.png'},
  {id: 3, name: 'manh', image: base_url+'A3.png'},
  {id: 4, name: 'manh', image: base_url+'A4.png'},
  {id: 5, name: 'manh', image: base_url+'A5.png'},
  {id: 6, name: 'manh', image: base_url+'A6.png'},
  {id: 7, name: 'manh', image: base_url+'A7.png'},
  {id: 8, name: 'manh', image: base_url+'A8.png'},
  {id: 9, name: 'manh', image: base_url+'A9.png'},
  {id: 10, name: 'manh', image: base_url+'A10.png'},
  {id: 11, name: 'manh', image: base_url+'A11.png'},
  {id: 12, name: 'manh', image: base_url+'A12.png'},
  {id: 13, name: 'manh', image: base_url+'A13.png'},
  {id: 14, name: 'manh', image: base_url+'A14.png'},
  {id: 15, name: 'manh', image: base_url+'A15.png'},
  {id: 16, name: 'manh', image: base_url+'A16.png'},

//   {id: 17, name: 'manh', image: base_url+'ihwlebeizo.png'},
//   {id: 18, name: 'manh', image: base_url+'oibqmdylek.png'},
//   {id: 19, name: 'manh', image: base_url+'birpzzxdbw.png'},
//   {id: 20, name: 'manh', image: base_url+'wydfytngxw.png'},

//   {id: 21, name: 'manh', image: base_url+'dcbrcgeikj.png'},
//   {id: 22, name: 'manh', image: base_url+'xnbpevapto.png'},
//   {id: 23, name: 'manh', image: base_url+'uilodxvmoy.png'},
//   {id: 24, name: 'manh', image: base_url+'lpezdxjokk.png'},
//   {id: 25, name: 'manh', image: base_url+'yyteinxjhs.png'},
//   {id: 26, name: 'manh', image: base_url+'dkjsnktdbu.png'},
//   {id: 27, name: 'manh', image: base_url+'lawwxveymn.png'},
//   {id: 28, name: 'manh', image: base_url+'hkwprfdwit.png'},
//   {id: 29, name: 'manh', image: base_url+'tvddfpktfz.png'},
//   {id: 30, name: 'manh', image: base_url+'grnftcgedj.png'},

//   {id: 31, name: 'manh', image: base_url+'advskbcsnq.png'},
//   {id: 32, name: 'manh', image: base_url+'qoekajycue.png'},
//   {id: 33, name: 'manh', image: base_url+'xlxiwplgjq.png'},
//   {id: 34, name: 'manh', image: base_url+'jdcwcfqaiy.png'},
//   {id: 35, name: 'manh', image: base_url+'ghoberzlbt.png'},
//   {id: 36, name: 'manh', image: base_url+'clwghrpmcj.png'},
//   {id: 37, name: 'manh', image: base_url+'qcrplzkffc.png'},
//   {id: 38, name: 'manh', image: base_url+'iwzxokzcpz.png'},
//   {id: 39, name: 'manh', image: base_url+'infmemzbeq.png'},
//   {id: 40, name: 'manh', image: base_url+'quciwiflek.png'},

//   {id: 41, name: 'manh', image: base_url+'awnxnvjhly.png'},
//   {id: 42, name: 'manh', image: base_url+'gaoxrtrfpr.png'},
//   {id: 43, name: 'manh', image: base_url+'akmxrutomf.png'},
//   {id: 44, name: 'manh', image: base_url+'vjdolnskpk.png'},
//   {id: 45, name: 'manh', image: base_url+'ypvgdnljnj.png'},
//   {id: 46, name: 'manh', image: base_url+'fsjcyygutb.png'},
//   {id: 47, name: 'manh', image: base_url+'wgajwzajqb.png'},
//   {id: 48, name: 'manh', image: base_url+'olxnoznwsx.png'},
//   {id: 49, name: 'manh', image: base_url+'wedqzjkdey.png'},
//   {id: 50, name: 'manh', image: base_url+'jeokcfqydy.png'},

//   {id: 51, name: 'manh', image: base_url+'gosu51.png'},
//   {id: 52, name: 'manh', image: base_url+'gosuoke.png'},
//   {id: 53, name: 'manh', image: base_url+'songkeo.png'},
//   {id: 54, name: 'manh', image: base_url+'alumu.png'},
]