require('./bootstrap');
import { createApp } from 'vue';
import App from './App.vue';
import "bootstrap/dist/css/bootstrap.min.css";
import "bootstrap";
import routes from '@/js/routers/index';
import VueAxios from 'vue-axios';
const app = createApp(App);
app.use(VueAxios, axios);
app.use(routes).mount('#app');